spring:
  jpa:
    show-sql: true
  docker:
    compose:
      enabled: true
      lifecycle-management: start-only

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
